Modern es
mozilla/dxr pull request #652
Opened 2017-08-22 08:34 UTC by scmikes

This pull contains the first set of code to upgrade dxr to a modern elasticsearch.  The final target is elasticsearsearch 5.x latest.

This pull target is elasticsearch 2.4.1.  elasticsearch 2.4.1 still supports fieldnames as the default. 5.5.5 and later requires the create index command to specify filednames in the index create statement.

Main Changes:
   - index property name changes.    payload property appears in 2 places.  Under region and ref. Change names to region_payload and ref_payload.   Various py code changes to support this change.

 

dxr index and multiple test cases failed if an index with the same name as the old index tried to be created.

I am not certain if the desired behavior for dxr index , reusing index name is:  delete old index, create new.   I explicitly coded this in es.py.  Please review, if not correct, will fix to correct flow.

3 unit tests fail dealing with url redirect.   I am not sure what path to take to address these three unit tests.

added environment variable to define default elasticsearch host used by dxr DXR_DEFAULT_ELASTICSEARCH_HOST.  This the host to use if no host is defined in any config file or passed in on the command line.  This can be set in docker-compose.yml or on the command line.  The default value is 127.0.0.1.

Note: this code functions on both 1.7.5 (current docker elasticsearch version).   To test with elasticsearch 2.4.1 and this code
    1) setup elasticsearch 2.4.1 server
    2) edit docker-compose.yml   DXR_DEFUALT_ELASTICSEARCH_HOST to 2.4.1 server
    3) make shell
    4) make test

Note 2:   this code has only been validiated the following way so far.  Unit tests are the key validation so far.
     1) run unit tests - 3 fail with redirect LOCATION requrest property value missing
     2) dxr index    vim code base
     3) dxr index our products csv files

Remaining Targets:
    1) switch to scmikes/dxr   modern-es-555 branch to work on 555 work
             - define index create statement to activate fieldnames (in theory, should behave the same as 1.7.5 and 2.4.1 default behavior)
             - change docker env setup to use elasticsearch 5.5.5 (or later if 5.5.6 released).  Target is 5.x
     2) fix 3 unit test cases that fail
     3) very light validation of dxr serve.  This has not been validated at all so far.  Unit tests are key validation tests with the 2.4.1

2017-08-22 14:20 UTC, erikrose requested changes
I just see some minor touch-ups to address so you can get this merged before embarking on the 5.5 stuff. Thanks again for your good work!

2017-08-22 14:20 UTC, erikrose commented on dxr/lines.py
> +
Let's fix [linter errors like this one](https://travis-ci.org/mozilla/dxr/builds/267092335#L2659-L2666) as we go so Travis will at least try to run the tests.

2017-08-22 14:20 UTC, erikrose commented on dxr/config.py
> +#setup default elasticsearch host to use if not specifice in any config file
"Set up" and "specified"

2017-08-22 14:20 UTC, erikrose commented on dxr/cli/serve.py
> +        default=DXR_DEFAULT_ELASTICSEARCH_HOST,
This is supposed to be the address the web serve itself listens on, not the ES host.

2017-08-22 14:20 UTC, erikrose commented on dxr/config.py
> +DXR_DEFAULT_ELASTICSEARCH_HOST = getenv('DXR_DEFAULT_ELASTICSEARCH_HOST', '127.0.0.1')
If we don't end up using this in serve.py, then we can collapse it into the next line.

2017-08-22 14:20 UTC, erikrose commented on dxr/es.py
> +#              wait_for_no_relocating_shards='true',  # wait for all
Did you mean to leave this commented out?

2017-08-22 14:20 UTC, erikrose commented on dxr/plugins/core.py
>                  'start': UNINDEXED_INT,
We should indent these lines inside the `properties` key.

2017-08-22 14:20 UTC, erikrose commented on dxr/plugins/core.py
>                  'start': UNINDEXED_INT,
These too.

2017-08-22 16:03 UTC, scmikes commented
Thanks Erik,

I will fix that and push that up.  I am away from my dev machine today.  I should be able to fix and push up tomorrow.

Michael Schneider
Sr Software Engineering Consultant
Tech & Innov

Siemens Industry Sector
Siemens Product Lifecycle Management Software Inc.
2000 Eastman Drive
Milford, OH  45150 United States
Tel.      :+1 (513) 576-2935
Fax      :+1 (513) 576-2734
michael.l.schneider@siemens.com <michael.l.schneider@siemens.com%20>
www.siemens.com/plm

From: Erik Rose [mailto:notifications@github.com]
Sent: Tuesday, August 22, 2017 10:21 AM
To: mozilla/dxr <dxr@noreply.github.com>
Cc: Schneider, Michael (DF PL TO TCO INF DO) <michael.l.schneider@siemens.com>; Author <author@noreply.github.com>
Subject: Re: [mozilla/dxr] Modern es (#652)


@erikrose requested changes on this pull request.

I just see some minor touch-ups to address so you can get this merged before embarking on the 5.5 stuff. Thanks again for your good work!

________________________________

In dxr/lines.py<https://github.com/mozilla/dxr/pull/652#discussion_r134489046>:

> @@ -120,8 +120,12 @@ def ref_class(plugin, id):

                 warn('Ref subclass from plugin %s with ID %s was referenced '

                      'in the index but not found in the current '

                      'implementation. Ignored.' % (plugin, id))

-

-        payload = es_data['payload']

+

Let's fix linter errors like this one<https://travis-ci.org/mozilla/dxr/builds/267092335#L2659-L2666> as we go so Travis will at least try to run the tests.

________________________________

In dxr/config.py<https://github.com/mozilla/dxr/pull/652#discussion_r134492091>:

> @@ -19,6 +20,11 @@

 from dxr.plugins import all_plugins_but_core, core_plugin

 from dxr.utils import cd, if_raises



+#setup default elasticsearch host to use if not specifice in any config file

"Set up" and "specified"

________________________________

In dxr/cli/serve.py<https://github.com/mozilla/dxr/pull/652#discussion_r134492522>:

> @@ -12,7 +13,7 @@

         flag_value='0.0.0.0',

         help='Serve on all interfaces.  Equivalent to --host 0.0.0.0')

 @option('--host', '-h',

-        default='localhost',

+        default=DXR_DEFAULT_ELASTICSEARCH_HOST,

This is supposed to be the address the web serve itself listens on, not the ES host.

________________________________

In dxr/config.py<https://github.com/mozilla/dxr/pull/652#discussion_r134493019>:

> @@ -19,6 +20,11 @@

 from dxr.plugins import all_plugins_but_core, core_plugin

 from dxr.utils import cd, if_raises



+#setup default elasticsearch host to use if not specifice in any config file

+DXR_DEFAULT_ELASTICSEARCH_HOST = getenv('DXR_DEFAULT_ELASTICSEARCH_HOST', '127.0.0.1')

If we don't end up using this in serve.py, then we can collapse it into the next line.

________________________________

In dxr/es.py<https://github.com/mozilla/dxr/pull/652#discussion_r134493201>:

>      es.health(index=index,

               wait_for_status='yellow',

-              wait_for_relocating_shards=0,  # wait for all

+#              wait_for_no_relocating_shards='true',  # wait for all

Did you mean to leave this commented out?

________________________________

In dxr/plugins/core.py<https://github.com/mozilla/dxr/pull/652#discussion_r134494488>:

> @@ -156,11 +154,10 @@

             },



             'refs': {

-                'type': 'object',

+                'properties': {

                 'start': UNINDEXED_INT,

We should indent these lines inside the properties key.

________________________________

In dxr/plugins/core.py<https://github.com/mozilla/dxr/pull/652#discussion_r134494580>:

>              },



             'regions': {

-                'type': 'object',

+                'properties':{

                 'start': UNINDEXED_INT,

These too.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/mozilla/dxr/pull/652#pullrequestreview-57786366>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AdouABcK3C-H3sleYicaXayKD98JqO8uks5sauO-gaJpZM4O-SRB>.

2017-08-30 17:38 UTC, erikrose commented
Looks good! There's just one missed spot in core.py where we should indent. Search for my "These too" comment. Thanks again!

2017-08-30 18:27 UTC, scmikes commented
Erik,



Will submit with next round of submits.  Working on 5.5.5.



Mike


----------------------------------------------------------
"The best performance improvement is the transition from the nonworking state to the working state." - John Ousterhout<http://www.answers.com/topic/john-ousterhout>

Michael Schneider - Senior Software Engineering Consultant
Siemens  PLM Software
________________________________
From: Erik Rose [notifications@github.com]
Sent: Wednesday, August 30, 2017 1:38 PM
To: mozilla/dxr
Cc: Schneider, Michael (DF PL TO TCO INF DO); Author
Subject: Re: [mozilla/dxr] Modern es (#652)


Looks good! There's just one missed spot in core.py where we should indent. Search for my "These too" comment. Thanks again!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/mozilla/dxr/pull/652#issuecomment-326065032>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AdouALEOBnvTVDGsQTk7WyDQGpwpuVq7ks5sdZ4ngaJpZM4O-SRB>.

2021-10-13 12:19 UTC, closed without merging